### ISSUE TITLE
Hacer que todo el sistema sea multi-sede

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#1]
- [x] Revisar todos los modelos para que cada instancia correponda a una sede
- [x] Hacer una página principal donde el visitante elija la sede que le interesa y vea toda la info pertinente a la misma
- [x] Definir cómo se van a establecer roles por sede (que los colaboradores de una sede puedan editar sólo la información de la sede que corresponde)

**Comment by reyiyo** [comment]
![home](https://cloud.githubusercontent.com/assets/761204/6545133/87e3a0d4-c555-11e4-8ba8-32a5058bd6ca.png)
![sede](https://cloud.githubusercontent.com/assets/761204/6545134/87e63402-c555-11e4-9840-5b0c177a0193.png)


Los ABM de administración se podrían hacer con ModelAdmin.queryset(). De esta forma, el usuario sólo vería los objetos correspondientes a su sede

**Comment by reyiyo** [comment]
Los ABM de administración se podrían hacer usando el admin de django y con ModelAdmin.queryset(). De esta forma, el usuario sólo vería los objetos correspondientes a su sede
